steps:

  - name: "bash"

    id: "set-tag-name"

    entrypoint: "bash"

    args:

      - "-c"

      - |
        # Set a simple tag name based on branch and commit
        if [[ "$BRANCH_NAME" == "main" ]]; then
          TAG_NAME="prod"
        else
          TAG_NAME="dev"
        fi
        echo TAG_NAME=$$TAG_NAME >> /workspace/build.env
        echo "Set TAG_NAME: $$TAG_NAME"

  - name: "gcr.io/cloud-builders/docker"

    id: "build-and-push"

    entrypoint: "bash"

    args:

      - "-c"

      - |
        source /workspace/build.env
        TAG="$${TAG_NAME}-${COMMIT_SHA}"
        IMAGE="us-central1-docker.pkg.dev/personal-website-480904/cloud-run-source-deploy/personal-site/personal-site:${COMMIT_SHA}"
        echo "Building image: $$IMAGE"
        docker build --platform linux/amd64 --file Dockerfile -t $$IMAGE .
        echo "Pushing image: $$IMAGE"
        docker push $$IMAGE
        if [ $? -ne 0 ]; then
          echo "ERROR: Failed to push image"
          exit 1
        fi
        echo "Successfully pushed image: $$IMAGE"
        echo IMAGE=$$IMAGE >> /workspace/build.env

  - name: "gcr.io/cloud-builders/gcloud"

    id: "deploy-to-cloud-run"

    entrypoint: "bash"

    args:

      - "-c"

      - |
        source /workspace/build.env
        echo "Deploying image $$IMAGE to Cloud Run"
        gcloud run deploy personal-site --image=$$IMAGE --region=us-central1 --platform=managed --port=80 --memory=128Mi --cpu=0.5 --min-instances=0 --max-instances=1 --allow-unauthenticated

timeout: 600s

logsBucket: gs://personal-website-480904-build-logs/personal-site

